/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.map;

import entities.*;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Jaime
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Declaraciones de atributos
     */
    private JLabel floorLayer_[][];  //  Tablero del suelo
    private JLabel entityLayer_[][]; //  Tablero de entidades
    int dimX_, dimY_;           //  Dimensiones del tablero

    private Entity agents_[];   //  Lista de agentes y obstáculo
    int nAgents_;               //  Lúmero de agentes obstáculo
    private Entity mainAgent_;  //  Agente principal (robot) (R2D2)

    private final ImageIcon floorTile_ = new ImageIcon( //  Tile que
            getClass() //  representa
            .getResource("defensive.png"));     //  el suelo

    private void floorGen() {
        floorLayer_ = new JLabel[dimX_][dimY_];
        screenPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        for (int i = 0; i < dimX_; i++) {
            for (int j = 0; j < dimY_; j++) {
                floorLayer_[i][j] = new JLabel();
                floorLayer_[i][j].setIcon(floorTile_);
                screenPanel.add(floorLayer_[i][j], new AbsoluteConstraints(i * 32, j * 32, 32, 32));
                pack();
            }
        }
    }

    public Screen(int dim_x, int dim_y) {
        initComponents();
        JLabel thumb = new JLabel();
        thumb.setIcon(new ImageIcon(getClass().getResource("defensive.png")));
        this.add(thumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 32, 32));
        setVisible(true);
        Entity mainAgent_ = new EntityR2D2();
        //floorTile_= new ImageIcon(getClass().getResource("defensive.png"));

        dimX_ = dim_x;
        dimY_ = dim_y;

        entityLayer_ = new JLabel[dim_x][dim_y];
        floorGen();

    }

    /**
     * Creates new form Screen
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout screenPanelLayout = new javax.swing.GroupLayout(screenPanel);
        screenPanel.setLayout(screenPanelLayout);
        screenPanelLayout.setHorizontalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        screenPanelLayout.setVerticalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel screenPanel;
    // End of variables declaration//GEN-END:variables
}
